[package]
name = "cal"
version = "0.1.0"
edition = "2021"
license = "MIT"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.6", features = ["cargo"] }
git-version = "0.3.9"
logos = "0.14.0"
thiserror = "1.0.61"
